version: "2.1"
services:
  iredmail:
    image: wx136/iredmail:nightly
    container_name: email
    environment:
      - HOSTNAME=meet.planavy.com
      - FIRST_MAIL_DOMAIN=planavy.com
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=123456
      - MLMMJADMIN_API_TOKEN=$(openssl rand -base64 32)
      - ROUNDCUBE_DES_KEY=$(openssl rand -base64 24)
      - MYSQL_ROOT_PASSWORD=admin@123
      - VMAIL_DB_PASSWORD=admin@123
      - VMAIL_DB_ADMIN_PASSWORD=admin@123
      - AMAVISD_DB_PASSWORD=admin@123
      - ROUNDCUBE_DB_PASSWORD=admin@123
      - IREDAPD_DB_PASSWORD=admin@123
      - IREDADMIN_DB_PASSWORD=admin@123
      - FAIL2BAN_DB_PASSWORD=admin@123
      - SA_BAYES_DB_PASSWORD=admin@123
      - MAIL_THE_TIP_FILE=NO
    volumes:
      - /data/life/email/backup-mysql:/var/vmail/backup/mysql
      - /data/life/email/mailboxes:/var/vmail/vmail1
      - /data/life/email/mlmmj:/var/vmail/mlmmj
      - /data/life/email/mlmmj-archive:/var/vmail/mlmmj-archive
      - /data/life/email/imapsieve_copy:/var/vmail/imapsieve_copy
      - /data/life/email/custom:/opt/iredmail/custom
      - /data/life/email/ssl:/opt/iredmail/ssl
      - /data/life/email/mysql:/var/lib/mysql
      - /data/life/email/clamav:/var/lib/clamav
      - /data/life/email/sa_rules:/var/lib/spamassassin
      - /data/life/email/postfix_queue:/var/spool/postfix
    ports:
      - 83:80
      - 4433:443
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 25:25
      - 465:465
      - 587:587
    restart: unless-stopped